In [1]:
import numpy as np

In [3]:
arr = [1, 2, 3, 4, 5]
np_arr = np.array(arr)
np_arr

array([1, 2, 3, 4, 5])

In [ ]:
#массив из нулей
zeros_array_1d = np.zeros(7)
print(zeros_array_1d)
zeros_array_1d.shape

[0. 0. 0. 0. 0. 0. 0.]


(7,)

In [10]:
#массив из единиц
ones_array = np.ones((3, 4))
print(f"type of data: {ones_array.dtype}")
ones_array.shape

type of data: float64


(3, 4)

In [18]:
np_array = np.arange(1, 15, 2)
print(np_array)
first_element = np_array[0] #получение первого элемента
pod_array = np_array[1:5:2] #извлечение подмассива
pod_array

[ 1  3  5  7  9 11 13]


array([3, 7])

In [ ]:
#сумма массивов
arr_for_sum = np.arange(1, 8)
sum_of_arrays = np_array + arr_for_sum
sum_of_arrays

array([ 2,  5,  8, 11, 14, 17, 20])

In [ ]:
#среднее
mean_value = np.mean(sum_of_arrays)
mean_value

np.float64(11.0)